version: '3.7'

services:
  db:
    image: postgres:14.5-alpine
    container_name: gofunky_db
    hostname: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/datas
  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
    container_name: gofunky_redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'

volumes:
  pgdata: